resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/22.yaml

packages:
- .

extra-include-dirs:
- /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/include/ffi

ghc-options:
  "$everything": -O0
