name: Haskell Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up GHC and Stack
      - name: Set up Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: "9.0.2"
          stack-version: "latest"

      # Step 3: Cache Stack (Optional for dependencies)
      - name: Cache Stack
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock') }}

      # Step 4: Install dependencies only (if needed)
      - name: Install dependencies
        run: stack setup && stack build --only-dependencies

      # Step 5: Run the tests without building the entire project
      - name: Run tests
        run: stack test --fast -j4

      # Step 6: Upload test logs if the tests fail (with v4)
      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            .stack-work/logs/
