name: Haskell CI

on:
  push:
    branches:
      - main # You can change this to whatever branch you want to run the tests on
  pull_request:
    branches:
      - main # Run tests on pull requests to `main` as well

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up GHC and Stack
      - name: Set up Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: "9.0.2"
          stack-version: "latest"

      # Step 3: Cache Stack dependencies to speed up future builds
      - name: Cache Stack
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock') }}

      # Step 4: Install dependencies (only dependencies are built here)
      - name: Install dependencies
        run: stack setup && stack build --only-dependencies

      # Step 5: Build and test the project
      - name: Build and test
        run: stack test --fast -j4

      # Step 6: Output test results (optional)
      - name: Upload test logs
        if: failure() # Only upload logs if the tests fail
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: |
            .stack-work/logs/
