name: Haskell Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Cache GHCup, GHC, Stack, and previous test outputs
      - name: Cache GHCup, Stack, and dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.ghcup           # Cache GHCup to avoid re-installing GHC/Stack
            ~/.stack           # Cache Stack environment (dependencies)
            .stack-work        # Cache local build outputs
          key: ${{ runner.os }}-stack-test-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-stack-test

      # Step 3: Set up GHC and Stack (only if not cached)
      - name: Set up Haskell (only if not cached)
        if: steps.cache.outputs.cache-hit != 'true'
        uses: haskell-actions/setup
        with:
          ghc-version: "9.0.2"
          stack-version: "latest"

      # Step 4: Run the stack test directly (without building the project)
      - name: Run tests
        run: stack test --fast -j4

      # Step 5: Upload test logs (if tests fail)
      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            .stack-work/logs/
